export const totalSkills = [
  { name: "C", class: "devicon-c-original" },
  { name: "Node.js", class: "devicon-nodejs-plain-wordmark" },
  { name: "React", class: "devicon-react-original" },
  { name: "MongoDB", class: "devicon-mongodb-plain-wordmark" },
  { name: "C++", class: "devicon-cplusplus-plain" },
  { name: "JavaScript", class: "devicon-javascript-plain" },
  { name: "Java", class: "devicon-java-plain-wordmark" },
  { name: "PHP", class: "devicon-php-plain" },
  { name: "Docker", class: "devicon-docker-plain" },
  { name: "Python", class: "devicon-python-plain" },
  { name: "HTML5", class: "devicon-html5-plain" },
  { name: "CSS3", class: "devicon-css3-plain" },
  { name: "Tailwind CSS", class: "devicon-tailwindcss-original" },
  { name: "Bootstrap", class: "devicon-bootstrap-plain" },
  { name: "TypeScript", class: "devicon-typescript-plain" },
  { name: "Next.js", class: "devicon-nextjs-original-wordmark" },
  { name: "Express", class: "devicon-express-original" },
  { name: "MySQL", class: "devicon-mysql-plain-wordmark" },
  { name: "PostgreSQL", class: "devicon-postgresql-plain-wordmark" },
  { name: "Firebase", class: "devicon-firebase-plain-wordmark" },
  { name: "Git", class: "devicon-git-plain-wordmark" },
  { name: "GitHub", class: "devicon-github-original" },
  { name: "AWS", class: "devicon-amazonwebservices-plain-wordmark" },
  { name: "Nginx", class: "devicon-nginx-original" },
  { name: "VS Code", class: "devicon-vscode-plain" },
  { name: "Figma", class: "devicon-figma-plain" },
  { name: "Canva", class: "devicon-canva-original" },
  { name: "Flask", class: "devicon-flask-original" },
  { name: "Socket.io", class: "devicon-socketio-original" },
  { name: "Django", class: "devicon-django-plain-wordmark" },
  { name: "GraphQL", class: "devicon-graphql-plain-wordmark" },
  { name: "Redux", class: "devicon-redux-original" },
  { name: "Go", class: "devicon-go-original-wordmark" },
  { name: "Angular", class: "devicon-angularjs-plain" },
  { name: "Vue.js", class: "devicon-vuejs-plain-wordmark" },
  { name: "Apache", class: "devicon-apache-plain-wordmark" },
  { name: "SASS", class: "devicon-sass-original" },
  { name: "Android", class: "devicon-android-plain" },
  { name: "React Native", class: "devicon-reactnative-original-wordmark" },
  { name: "Flutter", class: "devicon-flutter-plain" }
];
